version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd app/frontend
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building React application...
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build phase completed
      - echo Preparing artifacts...
      - cd dist
      - echo "S3_BUCKET=$S3_BUCKET"
      - echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID"
      - |
        if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
          echo "CloudFront cache invalidated successfully"
        else
          echo "Warning: CLOUDFRONT_DISTRIBUTION_ID not set, skipping cache invalidation"
        fi
artifacts:
  files:
    - '**/*'
  base-directory: app/frontend/dist

